# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MySDK
  pod 'Mixpanel-swift'

end
